/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ILoanManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approve"
      | "disburse"
      | "loans"
      | "nextId"
      | "repay"
      | "requestLoan"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Applied" | "Approved" | "Disbursed" | "Repaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disburse",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(functionFragment: "repay", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "requestLoan",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "disburse", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestLoan",
    data: BytesLike
  ): Result;
}

export namespace AppliedEvent {
  export type InputTuple = [
    id: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, borrower: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    borrower: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisbursedEvent {
  export type InputTuple = [
    id: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, borrower: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    borrower: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaidEvent {
  export type InputTuple = [
    id: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, borrower: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    borrower: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ILoanManager extends BaseContract {
  connect(runner?: ContractRunner | null): ILoanManager;
  waitForDeployment(): Promise<this>;

  interface: ILoanManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approve: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  disburse: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  loans: TypedContractMethod<
    [id: BigNumberish],
    [
      [string, bigint, boolean, boolean, bigint] & {
        borrower: string;
        amount: bigint;
        approved: boolean;
        disbursed: boolean;
        repaid: bigint;
      }
    ],
    "view"
  >;

  nextId: TypedContractMethod<[], [bigint], "view">;

  repay: TypedContractMethod<[id: BigNumberish], [void], "payable">;

  requestLoan: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disburse"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [string, bigint, boolean, boolean, bigint] & {
        borrower: string;
        amount: bigint;
        approved: boolean;
        disbursed: boolean;
        repaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<[id: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "requestLoan"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "nonpayable">;

  getEvent(
    key: "Applied"
  ): TypedContractEvent<
    AppliedEvent.InputTuple,
    AppliedEvent.OutputTuple,
    AppliedEvent.OutputObject
  >;
  getEvent(
    key: "Approved"
  ): TypedContractEvent<
    ApprovedEvent.InputTuple,
    ApprovedEvent.OutputTuple,
    ApprovedEvent.OutputObject
  >;
  getEvent(
    key: "Disbursed"
  ): TypedContractEvent<
    DisbursedEvent.InputTuple,
    DisbursedEvent.OutputTuple,
    DisbursedEvent.OutputObject
  >;
  getEvent(
    key: "Repaid"
  ): TypedContractEvent<
    RepaidEvent.InputTuple,
    RepaidEvent.OutputTuple,
    RepaidEvent.OutputObject
  >;

  filters: {
    "Applied(uint256,address,uint256)": TypedContractEvent<
      AppliedEvent.InputTuple,
      AppliedEvent.OutputTuple,
      AppliedEvent.OutputObject
    >;
    Applied: TypedContractEvent<
      AppliedEvent.InputTuple,
      AppliedEvent.OutputTuple,
      AppliedEvent.OutputObject
    >;

    "Approved(uint256)": TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;
    Approved: TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;

    "Disbursed(uint256,address,uint256)": TypedContractEvent<
      DisbursedEvent.InputTuple,
      DisbursedEvent.OutputTuple,
      DisbursedEvent.OutputObject
    >;
    Disbursed: TypedContractEvent<
      DisbursedEvent.InputTuple,
      DisbursedEvent.OutputTuple,
      DisbursedEvent.OutputObject
    >;

    "Repaid(uint256,address,uint256)": TypedContractEvent<
      RepaidEvent.InputTuple,
      RepaidEvent.OutputTuple,
      RepaidEvent.OutputObject
    >;
    Repaid: TypedContractEvent<
      RepaidEvent.InputTuple,
      RepaidEvent.OutputTuple,
      RepaidEvent.OutputObject
    >;
  };
}
