/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMemberRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "isMember" | "kycPassed" | "register" | "unregister"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MemberKycUpdated"
      | "MemberRegistered"
      | "MemberUnregistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "isMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "kycPassed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "register", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unregister",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "isMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "kycPassed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unregister", data: BytesLike): Result;
}

export namespace MemberKycUpdatedEvent {
  export type InputTuple = [account: AddressLike, kycPassed: boolean];
  export type OutputTuple = [account: string, kycPassed: boolean];
  export interface OutputObject {
    account: string;
    kycPassed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRegisteredEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberUnregisteredEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IMemberRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IMemberRegistry;
  waitForDeployment(): Promise<this>;

  interface: IMemberRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isMember: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  kycPassed: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  register: TypedContractMethod<[], [void], "nonpayable">;

  unregister: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isMember"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "kycPassed"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unregister"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "MemberKycUpdated"
  ): TypedContractEvent<
    MemberKycUpdatedEvent.InputTuple,
    MemberKycUpdatedEvent.OutputTuple,
    MemberKycUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MemberRegistered"
  ): TypedContractEvent<
    MemberRegisteredEvent.InputTuple,
    MemberRegisteredEvent.OutputTuple,
    MemberRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MemberUnregistered"
  ): TypedContractEvent<
    MemberUnregisteredEvent.InputTuple,
    MemberUnregisteredEvent.OutputTuple,
    MemberUnregisteredEvent.OutputObject
  >;

  filters: {
    "MemberKycUpdated(address,bool)": TypedContractEvent<
      MemberKycUpdatedEvent.InputTuple,
      MemberKycUpdatedEvent.OutputTuple,
      MemberKycUpdatedEvent.OutputObject
    >;
    MemberKycUpdated: TypedContractEvent<
      MemberKycUpdatedEvent.InputTuple,
      MemberKycUpdatedEvent.OutputTuple,
      MemberKycUpdatedEvent.OutputObject
    >;

    "MemberRegistered(address)": TypedContractEvent<
      MemberRegisteredEvent.InputTuple,
      MemberRegisteredEvent.OutputTuple,
      MemberRegisteredEvent.OutputObject
    >;
    MemberRegistered: TypedContractEvent<
      MemberRegisteredEvent.InputTuple,
      MemberRegisteredEvent.OutputTuple,
      MemberRegisteredEvent.OutputObject
    >;

    "MemberUnregistered(address)": TypedContractEvent<
      MemberUnregisteredEvent.InputTuple,
      MemberUnregisteredEvent.OutputTuple,
      MemberUnregisteredEvent.OutputObject
    >;
    MemberUnregistered: TypedContractEvent<
      MemberUnregisteredEvent.InputTuple,
      MemberUnregisteredEvent.OutputTuple,
      MemberUnregisteredEvent.OutputObject
    >;
  };
}
