/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILoanManager } from "./ILoanManager";
export type { IMemberRegistry } from "./IMemberRegistry";
export type { ISavingsPool } from "./ISavingsPool";
