/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LoanManager } from "./LoanManager";
export type { MemberRegistry } from "./MemberRegistry";
export type { SavingsPool } from "./SavingsPool";
