/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MemberRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "hasRequestedExit"
      | "isKycPassed"
      | "isRegistered"
      | "owner"
      | "registerMember"
      | "renounceOwnership"
      | "requestExit"
      | "transferOwnership"
      | "unregisterMember"
      | "updateKycStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExitRequested"
      | "MemberKycUpdated"
      | "MemberRegistered"
      | "MemberUnregistered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "hasRequestedExit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isKycPassed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerMember",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestExit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unregisterMember",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateKycStatus",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "hasRequestedExit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKycPassed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestExit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unregisterMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateKycStatus",
    data: BytesLike
  ): Result;
}

export namespace ExitRequestedEvent {
  export type InputTuple = [member: AddressLike];
  export type OutputTuple = [member: string];
  export interface OutputObject {
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberKycUpdatedEvent {
  export type InputTuple = [member: AddressLike, passed: boolean];
  export type OutputTuple = [member: string, passed: boolean];
  export interface OutputObject {
    member: string;
    passed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRegisteredEvent {
  export type InputTuple = [member: AddressLike];
  export type OutputTuple = [member: string];
  export interface OutputObject {
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberUnregisteredEvent {
  export type InputTuple = [member: AddressLike];
  export type OutputTuple = [member: string];
  export interface OutputObject {
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MemberRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MemberRegistry;
  waitForDeployment(): Promise<this>;

  interface: MemberRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hasRequestedExit: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  isKycPassed: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isRegistered: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerMember: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestExit: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unregisterMember: TypedContractMethod<[], [void], "nonpayable">;

  updateKycStatus: TypedContractMethod<
    [account: AddressLike, passed: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hasRequestedExit"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isKycPassed"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerMember"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestExit"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unregisterMember"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateKycStatus"
  ): TypedContractMethod<
    [account: AddressLike, passed: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ExitRequested"
  ): TypedContractEvent<
    ExitRequestedEvent.InputTuple,
    ExitRequestedEvent.OutputTuple,
    ExitRequestedEvent.OutputObject
  >;
  getEvent(
    key: "MemberKycUpdated"
  ): TypedContractEvent<
    MemberKycUpdatedEvent.InputTuple,
    MemberKycUpdatedEvent.OutputTuple,
    MemberKycUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MemberRegistered"
  ): TypedContractEvent<
    MemberRegisteredEvent.InputTuple,
    MemberRegisteredEvent.OutputTuple,
    MemberRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MemberUnregistered"
  ): TypedContractEvent<
    MemberUnregisteredEvent.InputTuple,
    MemberUnregisteredEvent.OutputTuple,
    MemberUnregisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ExitRequested(address)": TypedContractEvent<
      ExitRequestedEvent.InputTuple,
      ExitRequestedEvent.OutputTuple,
      ExitRequestedEvent.OutputObject
    >;
    ExitRequested: TypedContractEvent<
      ExitRequestedEvent.InputTuple,
      ExitRequestedEvent.OutputTuple,
      ExitRequestedEvent.OutputObject
    >;

    "MemberKycUpdated(address,bool)": TypedContractEvent<
      MemberKycUpdatedEvent.InputTuple,
      MemberKycUpdatedEvent.OutputTuple,
      MemberKycUpdatedEvent.OutputObject
    >;
    MemberKycUpdated: TypedContractEvent<
      MemberKycUpdatedEvent.InputTuple,
      MemberKycUpdatedEvent.OutputTuple,
      MemberKycUpdatedEvent.OutputObject
    >;

    "MemberRegistered(address)": TypedContractEvent<
      MemberRegisteredEvent.InputTuple,
      MemberRegisteredEvent.OutputTuple,
      MemberRegisteredEvent.OutputObject
    >;
    MemberRegistered: TypedContractEvent<
      MemberRegisteredEvent.InputTuple,
      MemberRegisteredEvent.OutputTuple,
      MemberRegisteredEvent.OutputObject
    >;

    "MemberUnregistered(address)": TypedContractEvent<
      MemberUnregisteredEvent.InputTuple,
      MemberUnregisteredEvent.OutputTuple,
      MemberUnregisteredEvent.OutputObject
    >;
    MemberUnregistered: TypedContractEvent<
      MemberUnregisteredEvent.InputTuple,
      MemberUnregisteredEvent.OutputTuple,
      MemberUnregisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
