/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "LoanManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LoanManager__factory>;
    getContractFactory(
      name: "MemberRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MemberRegistry__factory>;
    getContractFactory(
      name: "SavingsPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SavingsPool__factory>;
    getContractFactory(
      name: "ILoanManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILoanManager__factory>;
    getContractFactory(
      name: "IMemberRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMemberRegistry__factory>;
    getContractFactory(
      name: "ISavingsPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISavingsPool__factory>;
    getContractFactory(
      name: "MemberRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MemberRegistry__factory>;
    getContractFactory(
      name: "SavingsPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SavingsPool__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "LoanManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LoanManager>;
    getContractAt(
      name: "MemberRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MemberRegistry>;
    getContractAt(
      name: "SavingsPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SavingsPool>;
    getContractAt(
      name: "ILoanManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILoanManager>;
    getContractAt(
      name: "IMemberRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMemberRegistry>;
    getContractAt(
      name: "ISavingsPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISavingsPool>;
    getContractAt(
      name: "MemberRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MemberRegistry>;
    getContractAt(
      name: "SavingsPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SavingsPool>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "LoanManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LoanManager>;
    deployContract(
      name: "MemberRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MemberRegistry>;
    deployContract(
      name: "SavingsPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SavingsPool>;
    deployContract(
      name: "ILoanManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILoanManager>;
    deployContract(
      name: "IMemberRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMemberRegistry>;
    deployContract(
      name: "ISavingsPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISavingsPool>;
    deployContract(
      name: "MemberRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MemberRegistry>;
    deployContract(
      name: "SavingsPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SavingsPool>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "LoanManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LoanManager>;
    deployContract(
      name: "MemberRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MemberRegistry>;
    deployContract(
      name: "SavingsPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SavingsPool>;
    deployContract(
      name: "ILoanManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILoanManager>;
    deployContract(
      name: "IMemberRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMemberRegistry>;
    deployContract(
      name: "ISavingsPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISavingsPool>;
    deployContract(
      name: "MemberRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MemberRegistry>;
    deployContract(
      name: "SavingsPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SavingsPool>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
